export const CATEGORY = {
  GENERAL: "🔧 General",
  INTERACTIVE: "🎛️ Interactive",
  VISUALIZATION: "📊 Data Visualization",
  COMPONENTS: "🧩 Components",
  CHARTS: "📈 Charts",
  TABLES: "📊 Tables",
  GRIDS: "📊 Grids",
  STYLES: "🎨 Styles",
  THEMES: "🌈 Themes",
  ICONS: "🔍 Icons",
  TYPOGRAPHY: "🔤 Typography",
  ANIMATIONS: "🎞️ Animations",
  LAYOUT: "📐 Layout",
  FORMS: "📝 Forms",
  NAVIGATION: "🧭 Navigation",
  FEEDBACK: "🔔 Feedback",
  OVERLAYS: "🖼️ Overlays",
  MEDIA: "🎥 Media",
  UTILITIES: "🛠️ Utilities",
  ACCESSIBILITY: "♿ Accessibility",
  PERFORMANCE: "🔥 Performance",
  SECURITY: "🔒 Security",
};
