const nodes: any[] = [
  {
    id: "Adidas",
    name: "Adidas",
    label: "Adidas",
    shape: "rounded-square",
    image:
      "https://front-chicago-dev.datafabdevelopment.com/images/Adidas.png?156161651",
    group: 1,
    is_cluster: true,
    style: {
      width: 80,
      height: 80,
      backgroundColor: "#FFFFFF",
      padding: 5,
      borderColor: "#E2E4E7",
      borderWidth: 2,
      labelStyle: {
        color: "#868789",
        fontSize: 14,
        fontWeight: "700",
        backgroundColor: "none",
        padding: 0,
      },
    },
  },
  {
    id: "150.12.84.210",
    name: "150.12.84.210",
    label: "150.12.84.210",
    shape: "circle",
    image:
      "https://front-chicago-dev.datafabdevelopment.com/images/Person.png?65614641",
    group: 1,
    is_cluster: false,
    style: {
      backgroundColor: "#FFFFFF",
      padding: 7,
      borderColor: "#E2E4E7",
      borderWidth: 2,
      labelStyle: {
        color: "#868789",
        fontSize: 14,
        fontWeight: "700",
        backgroundColor: "none",
        padding: 0,
      },
    },
  },
  {
    id: "203.205.246.18",
    name: "203.205.246.18",
    label: "203.205.246.18",
    shape: "circle",
    image:
      "https://front-chicago-dev.datafabdevelopment.com/images/Person.png?65614641",
    group: 1,
    style: {
      backgroundColor: "#FFFFFF",
      padding: 7,
      borderColor: "#E2E4E7",
      borderWidth: 2,
      labelStyle: {
        color: "#868789",
        fontSize: 14,
        fontWeight: "700",
        backgroundColor: "none",
        padding: 0,
      },
    },
  },
  {
    id: "203.205.232.216",
    name: "203.205.232.216",
    label: "203.205.232.216",
    shape: "circle",
    image:
      "https://front-chicago-dev.datafabdevelopment.com/images/Person.png?65614641",
    group: 1,
    style: {
      backgroundColor: "#FFFFFF",
      padding: 7,
      borderColor: "#E2E4E7",
      borderWidth: 2,
      labelStyle: {
        color: "#868789",
        fontSize: 14,
        fontWeight: "700",
        backgroundColor: "none",
        padding: 0,
      },
    },
  },
  {
    id: "50.117.145.153",
    name: "50.117.145.153",
    label: "50.117.145.153",
    shape: "circle",
    image:
      "https://front-chicago-dev.datafabdevelopment.com/images/Person.png?65614641",
    group: 1,
    is_cluster: false,
    style: {
      backgroundColor: "#FFFFFF",
      padding: 7,
      borderColor: "#E2E4E7",
      borderWidth: 2,
      labelStyle: {
        color: "#868789",
        fontSize: 14,
        fontWeight: "700",
        backgroundColor: "none",
        padding: 0,
      },
    },
  },
  {
    id: "117.238.123.24",
    name: "117.238.123.24",
    label: "117.238.123.24",
    shape: "circle",
    image:
      "https://front-chicago-dev.datafabdevelopment.com/images/Person.png?65614641",
    group: 1,
    is_cluster: false,
    style: {
      backgroundColor: "#FFFFFF",
      padding: 7,
      borderColor: "#E2E4E7",
      borderWidth: 2,
      labelStyle: {
        color: "#868789",
        fontSize: 14,
        fontWeight: "700",
        backgroundColor: "none",
        padding: 0,
      },
    },
  },
  {
    id: "23.153.69.178",
    name: "23.153.69.178",
    label: "23.153.69.178",
    shape: "circle",
    image:
      "https://front-chicago-dev.datafabdevelopment.com/images/Person.png?65614641",
    group: 1,
    is_cluster: false,
    style: {
      backgroundColor: "#FFFFFF",
      padding: 7,
      borderColor: "#E2E4E7",
      borderWidth: 2,
      labelStyle: {
        color: "#868789",
        fontSize: 14,
        fontWeight: "700",
        backgroundColor: "none",
        padding: 0,
      },
    },
  },
  {
    id: "172.101.225.134",
    name: "172.101.225.134",
    label: "172.101.225.134",
    shape: "circle",
    image:
      "https://front-chicago-dev.datafabdevelopment.com/images/Person.png?65614641",
    group: 1,
    is_cluster: false,
    style: {
      backgroundColor: "#FFFFFF",
      padding: 7,
      borderColor: "#E2E4E7",
      borderWidth: 2,
      labelStyle: {
        color: "#868789",
        fontSize: 14,
        fontWeight: "700",
        backgroundColor: "none",
        padding: 0,
      },
    },
  },
  {
    id: "155.161.33.124",
    name: "155.161.33.124",
    label: "155.161.33.124",
    shape: "circle",
    image:
      "https://front-chicago-dev.datafabdevelopment.com/images/Case.png?65614641",
    group: 1,
    is_cluster: false,
    style: {
      backgroundColor: "#FFFFFF",
      padding: 7,
      borderColor: "#E2E4E7",
      borderWidth: 2,
      labelStyle: {
        color: "#868789",
        fontSize: 14,
        fontWeight: "700",
        backgroundColor: "none",
        padding: 0,
      },
    },
  },
  {
    id: "Reebok",
    name: "Reebok",
    label: "Reebok",
    shape: "rounded-square",
    image:
      "https://front-chicago-dev.datafabdevelopment.com/images/Reebok.png?156161651",
    group: 2,
    is_cluster: true,
    style: {
      width: 120,
      height: 120,
      backgroundColor: "#FFFFFF",
      padding: 5,
      borderColor: "#E2E4E7",
      borderWidth: 2,
      labelStyle: {
        color: "#868789",
        fontSize: 14,
        fontWeight: "700",
        backgroundColor: "none",
        padding: 0,
      },
    },
  },
  {
    id: "216.198.200.5",
    name: "216.198.200.5",
    label: "216.198.200.5",
    shape: "circle",
    image:
      "https://front-chicago-dev.datafabdevelopment.com/images/Person.png?65614641",
    group: 2,
    is_cluster: false,
    style: {
      backgroundColor: "#FFFFFF",
      padding: 7,
      borderColor: "#E2E4E7",
      borderWidth: 2,
      labelStyle: {
        color: "#868789",
        fontSize: 14,
        fontWeight: "700",
        backgroundColor: "none",
        padding: 0,
      },
    },
  },
  {
    id: "163.194.16.224",
    name: "163.194.16.224",
    label: "163.194.16.224",
    shape: "circle",
    image:
      "https://front-chicago-dev.datafabdevelopment.com/images/Person.png?65614641",
    group: 2,
    is_cluster: false,
    style: {
      backgroundColor: "#FFFFFF",
      padding: 7,
      borderColor: "#E2E4E7",
      borderWidth: 2,
      labelStyle: {
        color: "#868789",
        fontSize: 14,
        fontWeight: "700",
        backgroundColor: "none",
        padding: 0,
      },
    },
  },
  {
    id: "203.205.130.223",
    name: "203.205.130.223",
    label: "203.205.130.223",
    shape: "circle",
    image:
      "https://front-chicago-dev.datafabdevelopment.com/images/Person.png?65614641",
    group: 2,
    is_cluster: false,
    style: {
      backgroundColor: "#FFFFFF",
      padding: 7,
      borderColor: "#E2E4E7",
      borderWidth: 2,
      labelStyle: {
        color: "#868789",
        fontSize: 14,
        fontWeight: "700",
        backgroundColor: "none",
        padding: 0,
      },
    },
  },
  {
    id: "45.58.141.32",
    name: "45.58.141.32",
    label: "45.58.141.32",
    shape: "circle",
    image:
      "https://front-chicago-dev.datafabdevelopment.com/images/Person.png?65614641",
    group: 2,
    is_cluster: false,
    style: {
      backgroundColor: "#FFFFFF",
      padding: 7,
      borderColor: "#E2E4E7",
      borderWidth: 2,
      labelStyle: {
        color: "#868789",
        fontSize: 14,
        fontWeight: "700",
        backgroundColor: "none",
        padding: 0,
      },
    },
  },
  {
    id: "203.205.143.78",
    name: "203.205.143.78",
    label: "203.205.143.78",
    shape: "circle",
    image:
      "https://front-chicago-dev.datafabdevelopment.com/images/Case.png?65614641",
    group: 2,
    is_cluster: false,
    style: {
      backgroundColor: "#FFFFFF",
      padding: 7,
      borderColor: "#E2E4E7",
      borderWidth: 2,
      labelStyle: {
        color: "#868789",
        fontSize: 14,
        fontWeight: "700",
        backgroundColor: "none",
        padding: 0,
      },
    },
  },
  {
    id: "203.205.142.9",
    name: "203.205.142.9",
    label: "203.205.142.9",
    shape: "circle",
    image:
      "https://front-chicago-dev.datafabdevelopment.com/images/Person.png?65614641",
    group: 2,
    is_cluster: false,
    style: {
      backgroundColor: "#FFFFFF",
      padding: 7,
      borderColor: "#E2E4E7",
      borderWidth: 2,
      labelStyle: {
        color: "#868789",
        fontSize: 14,
        fontWeight: "700",
        backgroundColor: "none",
        padding: 0,
      },
    },
  },
  {
    id: "202.117.58.16",
    name: "202.117.58.16",
    label: "202.117.58.16",
    shape: "circle",
    image:
      "https://front-chicago-dev.datafabdevelopment.com/images/Person.png?65614641",
    group: 2,
    is_cluster: false,
    style: {
      backgroundColor: "#FFFFFF",
      padding: 7,
      borderColor: "#E2E4E7",
      borderWidth: 2,
      labelStyle: {
        color: "#868789",
        fontSize: 14,
        fontWeight: "700",
        backgroundColor: "none",
        padding: 0,
      },
    },
  },
  {
    id: "107.90.10.97",
    name: "107.90.10.97",
    label: "107.90.10.97",
    shape: "circle",
    image:
      "https://front-chicago-dev.datafabdevelopment.com/images/Person.png?65614641",
    group: 2,
    is_cluster: false,
    style: {
      backgroundColor: "#FFFFFF",
      padding: 7,
      borderColor: "#E2E4E7",
      borderWidth: 2,
      labelStyle: {
        color: "#868789",
        fontSize: 14,
        fontWeight: "700",
        backgroundColor: "none",
        padding: 0,
      },
    },
  },
  {
    id: "185.159.224.0",
    name: "185.159.224.0",
    label: "185.159.224.0",
    shape: "circle",
    image:
      "https://front-chicago-dev.datafabdevelopment.com/images/Case.png?65614641",
    group: 2,
    is_cluster: false,
    style: {
      backgroundColor: "#FFFFFF",
      padding: 7,
      borderColor: "#E2E4E7",
      borderWidth: 2,
      labelStyle: {
        color: "#868789",
        fontSize: 14,
        fontWeight: "700",
        backgroundColor: "none",
        padding: 0,
      },
    },
  },
  {
    id: "FiveTen",
    name: "FiveTen",
    label: "FiveTen",
    shape: "rounded-square",
    image:
      "https://front-chicago-dev.datafabdevelopment.com/images/FiveTen.png?465616",
    group: 3,
    is_cluster: true,
    style: {
      width: 80,
      height: 80,
      backgroundColor: "#FFFFFF",
      padding: 7,
      borderColor: "#E2E4E7",
      borderWidth: 2,
      labelStyle: {
        color: "#868789",
        fontSize: 14,
        fontWeight: "700",
        backgroundColor: "none",
        padding: 0,
      },
    },
  },
  {
    id: "23.236.1.68",
    name: "23.236.1.68",
    label: "23.236.1.68",
    shape: "circle",
    image:
      "https://front-chicago-dev.datafabdevelopment.com/images/Person.png?65614641",
    group: 3,
    is_cluster: false,
    style: {
      backgroundColor: "#FFFFFF",
      padding: 7,
      borderColor: "#E2E4E7",
      borderWidth: 2,
      labelStyle: {
        color: "#868789",
        fontSize: 14,
        fontWeight: "700",
        backgroundColor: "none",
        padding: 0,
      },
    },
  },
  {
    id: "168.129.95.44",
    name: "168.129.95.44",
    label: "168.129.95.44",
    shape: "circle",
    image:
      "https://front-chicago-dev.datafabdevelopment.com/images/Person.png?65614641",
    group: 3,
    is_cluster: false,
    style: {
      backgroundColor: "#FFFFFF",
      padding: 7,
      borderColor: "#E2E4E7",
      borderWidth: 2,
      labelStyle: {
        color: "#868789",
        fontSize: 14,
        fontWeight: "700",
        backgroundColor: "none",
        padding: 0,
      },
    },
  },
  {
    id: "203.205.133.219",
    name: "203.205.133.219",
    label: "203.205.133.219",
    shape: "circle",
    image:
      "https://front-chicago-dev.datafabdevelopment.com/images/Person.png?65614641",
    group: 3,
    is_cluster: false,
    style: {
      backgroundColor: "#FFFFFF",
      padding: 7,
      borderColor: "#E2E4E7",
      borderWidth: 2,
      labelStyle: {
        color: "#868789",
        fontSize: 14,
        fontWeight: "700",
        backgroundColor: "none",
        padding: 0,
      },
    },
  },
  {
    id: "163.194.187.108",
    name: "163.194.187.108",
    label: "163.194.187.108",
    shape: "circle",
    image:
      "https://front-chicago-dev.datafabdevelopment.com/images/Case.png?65614641",
    group: 3,
    is_cluster: false,
    style: {
      backgroundColor: "#FFFFFF",
      padding: 7,
      borderColor: "#E2E4E7",
      borderWidth: 2,
      labelStyle: {
        color: "#868789",
        fontSize: 14,
        fontWeight: "700",
        backgroundColor: "none",
        padding: 0,
      },
    },
  },
  {
    id: "23.119.48.172",
    name: "23.119.48.172",
    label: "23.119.48.172",
    shape: "circle",
    image:
      "https://front-chicago-dev.datafabdevelopment.com/images/Person.png?65614641",
    group: 3,
    is_cluster: false,
    style: {
      backgroundColor: "#FFFFFF",
      padding: 7,
      borderColor: "#E2E4E7",
      borderWidth: 2,
      labelStyle: {
        color: "#868789",
        fontSize: 14,
        fontWeight: "700",
        backgroundColor: "none",
        padding: 0,
      },
    },
  },
  {
    id: "163.194.255.165",
    name: "163.194.255.165",
    label: "163.194.255.165",
    shape: "circle",
    image:
      "https://front-chicago-dev.datafabdevelopment.com/images/Person.png?65614641",
    group: 3,
    is_cluster: false,
    style: {
      backgroundColor: "#FFFFFF",
      padding: 7,
      borderColor: "#E2E4E7",
      borderWidth: 2,
      labelStyle: {
        color: "#868789",
        fontSize: 14,
        fontWeight: "700",
        backgroundColor: "none",
        padding: 0,
      },
    },
  },
  {
    id: "172.113.4.157",
    name: "172.113.4.157",
    label: "172.113.4.157",
    shape: "circle",
    image:
      "https://front-chicago-dev.datafabdevelopment.com/images/Person.png?65614641",
    group: 3,
    is_cluster: false,
    style: {
      backgroundColor: "#FFFFFF",
      padding: 7,
      borderColor: "#E2E4E7",
      borderWidth: 2,
      labelStyle: {
        color: "#868789",
        fontSize: 14,
        fontWeight: "700",
        backgroundColor: "none",
        padding: 0,
      },
    },
  },
  {
    id: "206.120.142.182",
    name: "206.120.142.182",
    label: "206.120.142.182",
    shape: "circle",
    image:
      "https://front-chicago-dev.datafabdevelopment.com/images/Case.png?65614641",
    group: 3,
    is_cluster: false,
    style: {
      backgroundColor: "#FFFFFF",
      padding: 7,
      borderColor: "#E2E4E7",
      borderWidth: 2,
      labelStyle: {
        color: "#868789",
        fontSize: 14,
        fontWeight: "700",
        backgroundColor: "none",
        padding: 0,
      },
    },
  },
  {
    id: "Nike",
    name: "Nike",
    label: "Nike",
    shape: "rounded-square",
    image:
      "https://front-chicago-dev.datafabdevelopment.com/images/Org.png?775515",
    group: 4,
    is_cluster: true,
    style: {
      width: 80,
      height: 80,
      backgroundColor: "#FFFFFF",
      padding: 7,
      borderColor: "#E2E4E7",
      borderWidth: 2,
      labelStyle: {
        color: "#868789",
        fontSize: 14,
        fontWeight: "700",
        backgroundColor: "none",
        padding: 0,
      },
    },
  },
  {
    id: "58.135.234.148",
    name: "58.135.234.148",
    label: "58.135.234.148",
    shape: "circle",
    image:
      "https://front-chicago-dev.datafabdevelopment.com/images/Person.png?65614641",
    group: 4,
    is_cluster: false,
    style: {
      backgroundColor: "#FFFFFF",
      padding: 7,
      borderColor: "#E2E4E7",
      borderWidth: 2,
      labelStyle: {
        color: "#868789",
        fontSize: 14,
        fontWeight: "700",
        backgroundColor: "none",
        padding: 0,
      },
    },
  },
  {
    id: "150.12.195.24",
    name: "150.12.195.24",
    label: "150.12.195.24",
    shape: "circle",
    image:
      "https://front-chicago-dev.datafabdevelopment.com/images/Person.png?65614641",
    group: 4,
    is_cluster: false,
    style: {
      backgroundColor: "#FFFFFF",
      padding: 7,
      borderColor: "#E2E4E7",
      borderWidth: 2,
      labelStyle: {
        color: "#868789",
        fontSize: 14,
        fontWeight: "700",
        backgroundColor: "none",
        padding: 0,
      },
    },
  },
  {
    id: "221.19.198.5",
    name: "221.19.198.5",
    label: "221.19.198.5",
    shape: "circle",
    image:
      "https://front-chicago-dev.datafabdevelopment.com/images/Person.png?65614641",
    group: 4,
    is_cluster: false,
    style: {
      backgroundColor: "#FFFFFF",
      padding: 7,
      borderColor: "#E2E4E7",
      borderWidth: 2,
      labelStyle: {
        color: "#868789",
        fontSize: 14,
        fontWeight: "700",
        backgroundColor: "none",
        padding: 0,
      },
    },
  },
  {
    id: "51.0.188.40",
    name: "51.0.188.40",
    label: "51.0.188.40",
    shape: "circle",
    image:
      "https://front-chicago-dev.datafabdevelopment.com/images/Case.png?65614641",
    group: 4,
    is_cluster: false,
    style: {
      backgroundColor: "#FFFFFF",
      padding: 7,
      borderColor: "#E2E4E7",
      borderWidth: 2,
      labelStyle: {
        color: "#868789",
        fontSize: 14,
        fontWeight: "700",
        backgroundColor: "none",
        padding: 0,
      },
    },
  },
  {
    id: "107.85.89.157",
    name: "107.85.89.157",
    label: "107.85.89.157",
    shape: "circle",
    image:
      "https://front-chicago-dev.datafabdevelopment.com/images/Person.png?65614641",
    group: 4,
    is_cluster: false,
    style: {
      backgroundColor: "#FFFFFF",
      padding: 7,
      borderColor: "#E2E4E7",
      borderWidth: 2,
      labelStyle: {
        color: "#868789",
        fontSize: 14,
        fontWeight: "700",
        backgroundColor: "none",
        padding: 0,
      },
    },
  },
  {
    id: "203.205.143.177",
    name: "203.205.143.177",
    label: "203.205.143.177",
    shape: "circle",
    image:
      "https://front-chicago-dev.datafabdevelopment.com/images/Person.png?65614641",
    group: 4,
    is_cluster: false,
    style: {
      backgroundColor: "#FFFFFF",
      padding: 7,
      borderColor: "#E2E4E7",
      borderWidth: 2,
      labelStyle: {
        color: "#868789",
        fontSize: 14,
        fontWeight: "700",
        backgroundColor: "none",
        padding: 0,
      },
    },
  },

  {
    id: "Armani",
    name: "Armani",
    label: "Armani",
    shape: "rounded-square",
    image:
      "https://front-chicago-dev.datafabdevelopment.com/images/Org.png?775515",
    group: 5,
    is_cluster: true,
    style: {
      width: 80,
      height: 80,
      backgroundColor: "#FFFFFF",
      padding: 7,
      borderColor: "#E2E4E7",
      borderWidth: 2,
      labelStyle: {
        color: "#868789",
        fontSize: 14,
        fontWeight: "700",
        backgroundColor: "none",
        padding: 0,
      },
    },
  },
  {
    id: "163.194.103.98",
    name: "163.194.103.98",
    label: "163.194.103.98",
    shape: "circle",
    image:
      "https://front-chicago-dev.datafabdevelopment.com/images/Case.png?65614641",
    group: 5,
    is_cluster: false,
    style: {
      backgroundColor: "#FFFFFF",
      padding: 7,
      borderColor: "#E2E4E7",
      borderWidth: 2,
      labelStyle: {
        color: "#868789",
        fontSize: 14,
        fontWeight: "700",
        backgroundColor: "none",
        padding: 0,
      },
    },
  },
  {
    id: "220.180.223.107",
    name: "220.180.223.107",
    label: "220.180.223.107",
    shape: "circle",
    image:
      "https://front-chicago-dev.datafabdevelopment.com/images/Person.png?65614641",
    group: 5,
    is_cluster: false,
    style: {
      backgroundColor: "#FFFFFF",
      padding: 7,
      borderColor: "#E2E4E7",
      borderWidth: 2,
      labelStyle: {
        color: "#868789",
        fontSize: 14,
        fontWeight: "700",
        backgroundColor: "none",
        padding: 0,
      },
    },
  },
  {
    id: "163.194.185.27",
    name: "163.194.185.27",
    label: "163.194.185.27",
    shape: "circle",
    image:
      "https://front-chicago-dev.datafabdevelopment.com/images/Person.png?65614641",
    group: 5,
    is_cluster: false,
    style: {
      backgroundColor: "#FFFFFF",
      padding: 7,
      borderColor: "#E2E4E7",
      borderWidth: 2,
      labelStyle: {
        color: "#868789",
        fontSize: 14,
        fontWeight: "700",
        backgroundColor: "none",
        padding: 0,
      },
    },
  },
  {
    id: "110.66.153.186",
    name: "110.66.153.186",
    label: "110.66.153.186",
    shape: "circle",
    image:
      "https://front-chicago-dev.datafabdevelopment.com/images/Person.png?65614641",
    group: 5,
    is_cluster: false,
    style: {
      backgroundColor: "#FFFFFF",
      padding: 7,
      borderColor: "#E2E4E7",
      borderWidth: 2,
      labelStyle: {
        color: "#868789",
        fontSize: 14,
        fontWeight: "700",
        backgroundColor: "none",
        padding: 0,
      },
    },
  },
  {
    id: "216.198.200.60",
    name: "216.198.200.60",
    label: "216.198.200.60",
    shape: "circle",
    image:
      "https://front-chicago-dev.datafabdevelopment.com/images/Case.png?65614641",
    group: 5,
    is_cluster: false,
    style: {
      backgroundColor: "#FFFFFF",
      padding: 7,
      borderColor: "#E2E4E7",
      borderWidth: 2,
      labelStyle: {
        color: "#868789",
        fontSize: 14,
        fontWeight: "700",
        backgroundColor: "none",
        padding: 0,
      },
    },
  },
  {
    id: "163.194.177.254",
    name: "163.194.177.254",
    label: "163.194.177.254",
    shape: "circle",
    image:
      "https://front-chicago-dev.datafabdevelopment.com/images/Person.png?65614641",
    group: 5,
    is_cluster: false,
    style: {
      backgroundColor: "#FFFFFF",
      padding: 7,
      borderColor: "#E2E4E7",
      borderWidth: 2,
      labelStyle: {
        color: "#868789",
        fontSize: 14,
        fontWeight: "700",
        backgroundColor: "none",
        padding: 0,
      },
    },
  },
];

const links: any[] = [
  {
    source: "Adidas",
    target: "150.12.84.210",
    label: "Director",
    type: "solid",
    message: "",
    style: {
      linkColor: "#C4C8CE",
      linkWidth: 1.5,
      linkType: "solid",
      labelStyle: {
        color: "#d2e6eb",
        fontSize: 9,
        fontWeight: "500",
        backgroundColor: "#81878F",
        padding: 3,
      },
      messageStyle: null,
    },
  },
  {
    source: "Adidas",
    target: "203.205.246.18",
    label: "Director",
    type: "solid",
    message: "",
    style: {
      linkColor: "#C4C8CE",
      linkWidth: 2,
      linkType: "solid",
      labelStyle: {
        color: "#d2e6eb",
        fontSize: 9,
        fontWeight: "500",
        backgroundColor: "#81878F",
        padding: 3,
      },
      messageStyle: null,
    },
  },
  {
    source: "Adidas",
    target: "203.205.232.216",
    label: "Director",
    type: "solid",
    message: "",
    style: {
      linkColor: "#C4C8CE",
      linkWidth: 2.5,
      linkType: "solid",
      labelStyle: {
        color: "#d2e6eb",
        fontSize: 9,
        fontWeight: "500",
        backgroundColor: "#81878F",
        padding: 3,
      },
      messageStyle: null,
    },
  },
  {
    source: "Adidas",
    target: "50.117.145.153",
    label: "Director",
    type: "solid",
    message: "",
    style: {
      linkColor: "#C4C8CE",
      linkWidth: 2.5,
      linkType: "solid",
      labelStyle: {
        color: "#d2e6eb",
        fontSize: 9,
        fontWeight: "500",
        backgroundColor: "#81878F",
        padding: 3,
      },
      messageStyle: null,
    },
  },
  {
    source: "Adidas",
    target: "117.238.123.24",
    label: "Director",
    type: "solid",
    message: "",
    style: {
      linkColor: "#C4C8CE",
      linkWidth: 5,
      linkType: "solid",
      labelStyle: {
        color: "#d2e6eb",
        fontSize: 9,
        fontWeight: "500",
        backgroundColor: "#81878F",
        padding: 3,
      },
      messageStyle: null,
    },
  },
  {
    source: "Adidas",
    target: "23.153.69.178",
    label: "Director",
    type: "solid",
    message: "",
    style: {
      linkColor: "#C4C8CE",
      linkWidth: 2,
      linkType: "solid",
      labelStyle: {
        color: "#d2e6eb",
        fontSize: 9,
        fontWeight: "500",
        backgroundColor: "#81878F",
        padding: 3,
      },
      messageStyle: null,
    },
  },
  {
    source: "Adidas",
    target: "172.101.225.134",
    label: "Director",
    type: "solid",
    message: "",
    style: {
      linkColor: "#C4C8CE",
      linkWidth: 4,
      linkType: "solid",
      labelStyle: {
        color: "#d2e6eb",
        fontSize: 9,
        fontWeight: "500",
        backgroundColor: "#81878F",
        padding: 3,
      },
      messageStyle: null,
    },
  },
  {
    source: "Adidas",
    target: "155.161.33.124",
    label: "Director",
    type: "solid",
    message: "",
    style: {
      linkColor: "#C4C8CE",
      linkWidth: 1.5,
      linkType: "solid",
      labelStyle: {
        color: "#d2e6eb",
        fontSize: 9,
        fontWeight: "500",
        backgroundColor: "#81878F",
        padding: 3,
      },
      messageStyle: null,
    },
  },
  {
    source: "Reebok",
    target: "Adidas",
    label: "Director",
    type: "solid",
    shape: "curved",
    message: "",
    style: {
      linkColor: "#C4C8CE",
      linkWidth: 1.5,
      linkType: "solid",
      labelStyle: {
        color: "#d2e6eb",
        fontSize: 9,
        fontWeight: "500",
        backgroundColor: "#81878F",
        padding: 3,
      },
      messageStyle: null,
    },
  },
  {
    source: "Reebok",
    target: "216.198.200.5",
    label: "Director",
    type: "solid",
    message: "",
    style: {
      linkColor: "#C4C8CE",
      linkWidth: 2,
      linkType: "solid",
      labelStyle: {
        color: "#d2e6eb",
        fontSize: 9,
        fontWeight: "500",
        backgroundColor: "#81878F",
        padding: 3,
      },
      messageStyle: null,
    },
  },
  {
    source: "Reebok",
    target: "163.194.16.224",
    label: "Director",
    type: "solid",
    message: "",
    style: {
      linkColor: "#C4C8CE",
      linkWidth: 2.5,
      linkType: "solid",
      labelStyle: {
        color: "#d2e6eb",
        fontSize: 9,
        fontWeight: "500",
        backgroundColor: "#81878F",
        padding: 3,
      },
      messageStyle: null,
    },
  },
  {
    source: "Reebok",
    target: "203.205.130.223",
    label: "Director",
    type: "solid",
    message: "",
    style: {
      linkColor: "#C4C8CE",
      linkWidth: 0.5,
      linkType: "solid",
      labelStyle: {
        color: "#d2e6eb",
        fontSize: 9,
        fontWeight: "500",
        backgroundColor: "#81878F",
        padding: 3,
      },
      messageStyle: null,
    },
  },
  {
    source: "Reebok",
    target: "45.58.141.32",
    label: "Director",
    type: "solid",
    message: "",
    style: {
      linkColor: "#C4C8CE",
      linkWidth: 4,
      linkType: "solid",
      labelStyle: {
        color: "#d2e6eb",
        fontSize: 9,
        fontWeight: "500",
        backgroundColor: "#81878F",
        padding: 3,
      },
      messageStyle: null,
    },
  },
  {
    source: "Reebok",
    target: "203.205.143.78",
    label: "Director",
    type: "solid",
    message: "",
    style: {
      linkColor: "#C4C8CE",
      linkWidth: 5,
      linkType: "solid",
      labelStyle: {
        color: "#d2e6eb",
        fontSize: 9,
        fontWeight: "500",
        backgroundColor: "#81878F",
        padding: 3,
      },
      messageStyle: null,
    },
  },
  {
    source: "Reebok",
    target: "203.205.142.9",
    label: "Director",
    type: "solid",
    message: "",
    style: {
      linkColor: "#C4C8CE",
      linkWidth: 2,
      linkType: "solid",
      labelStyle: {
        color: "#d2e6eb",
        fontSize: 9,
        fontWeight: "500",
        backgroundColor: "#81878F",
        padding: 3,
      },
      messageStyle: null,
    },
  },
  {
    source: "Reebok",
    target: "202.117.58.16",
    label: "Director",
    type: "solid",
    message: "",
    style: {
      linkColor: "#C4C8CE",
      linkWidth: 2,
      linkType: "solid",
      labelStyle: {
        color: "#d2e6eb",
        fontSize: 9,
        fontWeight: "500",
        backgroundColor: "#81878F",
        padding: 3,
      },
      messageStyle: null,
    },
  },
  {
    source: "Reebok",
    target: "107.90.10.97",
    label: "Director",
    type: "solid",
    message: "",
    style: {
      linkColor: "#C4C8CE",
      linkWidth: 2,
      linkType: "solid",
      labelStyle: {
        color: "#d2e6eb",
        fontSize: 9,
        fontWeight: "500",
        backgroundColor: "#81878F",
        padding: 3,
      },
      messageStyle: null,
    },
  },
  {
    source: "Reebok",
    target: "185.159.224.0",
    label: "Director",
    type: "solid",
    message: "",
    style: {
      linkColor: "#C4C8CE",
      linkWidth: 1.5,
      linkType: "solid",
      labelStyle: {
        color: "#d2e6eb",
        fontSize: 9,
        fontWeight: "500",
        backgroundColor: "#81878F",
        padding: 3,
      },
      messageStyle: null,
    },
  },
  {
    source: "Reebok",
    target: "FiveTen",
    label: "Director",
    type: "solid",
    shape: "curved",
    message: "",
    style: {
      linkColor: "#C4C8CE",
      linkWidth: 1.5,
      linkType: "solid",
      labelStyle: {
        color: "#d2e6eb",
        fontSize: 9,
        fontWeight: "500",
        backgroundColor: "#81878F",
        padding: 3,
      },
      messageStyle: null,
    },
  },
  {
    source: "FiveTen",
    target: "23.236.1.68",
    label: "Director",
    type: "solid",
    message: "",
    style: {
      linkColor: "#C4C8CE",
      linkWidth: 0.5,
      linkType: "solid",
      labelStyle: {
        color: "#d2e6eb",
        fontSize: 9,
        fontWeight: "500",
        backgroundColor: "#81878F",
        padding: 3,
      },
      messageStyle: null,
    },
  },
  {
    source: "FiveTen",
    target: "168.129.95.44",
    label: "Director",
    type: "solid",
    message: "",
    style: {
      linkColor: "#C4C8CE",
      linkWidth: 2,
      linkType: "solid",
      labelStyle: {
        color: "#d2e6eb",
        fontSize: 9,
        fontWeight: "500",
        backgroundColor: "#81878F",
        padding: 3,
      },
      messageStyle: null,
    },
  },
  {
    source: "FiveTen",
    target: "203.205.133.219",
    label: "Director",
    type: "solid",
    message: "",
    style: {
      linkColor: "#C4C8CE",
      linkWidth: 2,
      linkType: "solid",
      labelStyle: {
        color: "#d2e6eb",
        fontSize: 9,
        fontWeight: "500",
        backgroundColor: "#81878F",
        padding: 3,
      },
      messageStyle: null,
    },
  },
  {
    source: "FiveTen",
    target: "163.194.187.108",
    label: "Director",
    type: "solid",
    message: "",
    style: {
      linkColor: "#C4C8CE",
      linkWidth: 2.5,
      linkType: "solid",
      labelStyle: {
        color: "#d2e6eb",
        fontSize: 9,
        fontWeight: "500",
        backgroundColor: "#81878F",
        padding: 3,
      },
      messageStyle: null,
    },
  },
  {
    source: "FiveTen",
    target: "23.119.48.172",
    label: "Director",
    type: "solid",
    message: "",
    style: {
      linkColor: "#C4C8CE",
      linkWidth: 2,
      linkType: "solid",
      labelStyle: {
        color: "#d2e6eb",
        fontSize: 9,
        fontWeight: "500",
        backgroundColor: "#81878F",
        padding: 3,
      },
      messageStyle: null,
    },
  },
  {
    source: "FiveTen",
    target: "163.194.255.165",
    label: "Director",
    type: "solid",
    message: "",
    style: {
      linkColor: "#C4C8CE",
      linkWidth: 2.5,
      linkType: "solid",
      labelStyle: {
        color: "#d2e6eb",
        fontSize: 9,
        fontWeight: "500",
        backgroundColor: "#81878F",
        padding: 3,
      },
      messageStyle: null,
    },
  },
  {
    source: "FiveTen",
    target: "172.113.4.157",
    label: "Director",
    type: "solid",
    message: "",
    style: {
      linkColor: "#C4C8CE",
      linkWidth: 1.5,
      linkType: "solid",
      labelStyle: {
        color: "#d2e6eb",
        fontSize: 9,
        fontWeight: "500",
        backgroundColor: "#81878F",
        padding: 3,
      },
      messageStyle: null,
    },
  },
  {
    source: "FiveTen",
    target: "206.120.142.182",
    label: "Director",
    type: "solid",
    message: "",
    style: {
      linkColor: "#C4C8CE",
      linkWidth: 4,
      linkType: "solid",
      labelStyle: {
        color: "#d2e6eb",
        fontSize: 9,
        fontWeight: "500",
        backgroundColor: "#81878F",
        padding: 3,
      },
      messageStyle: null,
    },
  },
  {
    source: "Reebok",
    target: "Nike",
    label: "Director",
    type: "solid",
    shape: "curved",
    message: "",
    style: {
      linkColor: "#C4C8CE",
      linkWidth: 1.5,
      linkType: "solid",
      labelStyle: {
        color: "#d2e6eb",
        fontSize: 9,
        fontWeight: "500",
        backgroundColor: "#81878F",
        padding: 3,
      },
      messageStyle: null,
    },
  },
  {
    source: "Nike",
    target: "58.135.234.148",
    label: "Director",
    type: "solid",
    message: "",
    style: {
      linkColor: "#C4C8CE",
      linkWidth: 4,
      linkType: "solid",
      labelStyle: {
        color: "#d2e6eb",
        fontSize: 9,
        fontWeight: "500",
        backgroundColor: "#81878F",
        padding: 3,
      },
      messageStyle: null,
    },
  },
  {
    source: "Nike",
    target: "150.12.195.24",
    label: "Director",
    type: "solid",
    message: "",
    style: {
      linkColor: "#C4C8CE",
      linkWidth: 2,
      linkType: "solid",
      labelStyle: {
        color: "#d2e6eb",
        fontSize: 9,
        fontWeight: "500",
        backgroundColor: "#81878F",
        padding: 3,
      },
      messageStyle: null,
    },
  },
  {
    source: "Nike",
    target: "221.19.198.5",
    label: "Director",
    type: "solid",
    message: "",
    style: {
      linkColor: "#C4C8CE",
      linkWidth: 4,
      linkType: "solid",
      labelStyle: {
        color: "#d2e6eb",
        fontSize: 9,
        fontWeight: "500",
        backgroundColor: "#81878F",
        padding: 3,
      },
      messageStyle: null,
    },
  },
  {
    source: "Nike",
    target: "51.0.188.40",
    label: "Director",
    type: "solid",
    message: "",
    style: {
      linkColor: "#C4C8CE",
      linkWidth: 4,
      linkType: "solid",
      labelStyle: {
        color: "#d2e6eb",
        fontSize: 9,
        fontWeight: "500",
        backgroundColor: "#81878F",
        padding: 3,
      },
      messageStyle: null,
    },
  },
  {
    source: "Nike",
    target: "107.85.89.157",
    label: "Director",
    type: "solid",
    message: "",
    style: {
      linkColor: "#C4C8CE",
      linkWidth: 2,
      linkType: "solid",
      labelStyle: {
        color: "#d2e6eb",
        fontSize: 9,
        fontWeight: "500",
        backgroundColor: "#81878F",
        padding: 3,
      },
      messageStyle: null,
    },
  },
  {
    source: "Nike",
    target: "203.205.143.177",
    label: "Director",
    type: "solid",
    message: "",
    style: {
      linkColor: "#C4C8CE",
      linkWidth: 4,
      linkType: "solid",
      labelStyle: {
        color: "#d2e6eb",
        fontSize: 9,
        fontWeight: "500",
        backgroundColor: "#81878F",
        padding: 3,
      },
      messageStyle: null,
    },
  },
  {
    source: "Reebok",
    target: "Armani",
    label: "Director",
    type: "solid",
    shape: "curved",
    message: "",
    style: {
      linkColor: "#C4C8CE",
      linkWidth: 1.5,
      linkType: "solid",
      labelStyle: {
        color: "#d2e6eb",
        fontSize: 9,
        fontWeight: "500",
        backgroundColor: "#81878F",
        padding: 3,
      },
      messageStyle: null,
    },
  },
  {
    source: "Armani",
    target: "163.194.103.98",
    label: "Director",
    type: "solid",
    message: "",
    style: {
      linkColor: "#C4C8CE",
      linkWidth: 2,
      linkType: "solid",
      labelStyle: {
        color: "#d2e6eb",
        fontSize: 9,
        fontWeight: "500",
        backgroundColor: "#81878F",
        padding: 3,
      },
      messageStyle: null,
    },
  },
  {
    source: "Armani",
    target: "220.180.223.107",
    label: "Director",
    type: "solid",
    message: "",
    style: {
      linkColor: "#C4C8CE",
      linkWidth: 2,
      linkType: "solid",
      labelStyle: {
        color: "#d2e6eb",
        fontSize: 9,
        fontWeight: "500",
        backgroundColor: "#81878F",
        padding: 3,
      },
      messageStyle: null,
    },
  },
  {
    source: "Armani",
    target: "163.194.185.27",
    label: "Director",
    type: "solid",
    message: "",
    style: {
      linkColor: "#C4C8CE",
      linkWidth: 2,
      linkType: "solid",
      labelStyle: {
        color: "#d2e6eb",
        fontSize: 9,
        fontWeight: "500",
        backgroundColor: "#81878F",
        padding: 3,
      },
      messageStyle: null,
    },
  },
  {
    source: "Armani",
    target: "110.66.153.186",
    label: "Director",
    type: "solid",
    message: "",
    style: {
      linkColor: "#C4C8CE",
      linkWidth: 2,
      linkType: "solid",
      labelStyle: {
        color: "#d2e6eb",
        fontSize: 9,
        fontWeight: "500",
        backgroundColor: "#81878F",
        padding: 3,
      },
      messageStyle: null,
    },
  },
  {
    source: "Armani",
    target: "216.198.200.60",
    label: "Director",
    type: "solid",
    message: "",
    style: {
      linkColor: "#C4C8CE",
      linkWidth: 2,
      linkType: "solid",
      labelStyle: {
        color: "#d2e6eb",
        fontSize: 9,
        fontWeight: "500",
        backgroundColor: "#81878F",
        padding: 3,
      },
      messageStyle: null,
    },
  },
  {
    source: "Armani",
    target: "163.194.177.254",
    label: "Director",
    type: "solid",
    message: "",
    style: {
      linkColor: "#C4C8CE",
      linkWidth: 2,
      linkType: "solid",
      labelStyle: {
        color: "#d2e6eb",
        fontSize: 9,
        fontWeight: "500",
        backgroundColor: "#81878F",
        padding: 3,
      },
      messageStyle: null,
    },
  },
];

const clusters = [
  {
    id: "group1",
    color: "#f5f5f5",
    strength: 1,
    padding: 50,
  },
  {
    id: "group2",
    color: "#f5f5f5",
    strength: 1,
    padding: 50,
  },
  {
    id: "group3",
    color: "#f5f5f5",
    strength: 1,
    padding: 50,
  },
  {
    id: "bridge",
    color: "#ffffff",
    strength: 0.3,
    padding: 100,
  },
];

export { nodes, links, clusters };
